_wandb:
    value:
        cli_version: 0.25.0
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 12
            "3":
                - 13
                - 15
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
batch_size:
    value: 32
embed_dim:
    value: 32
epochs:
    value: 200
grad_clip_norm:
    value: 1
hidden_dim:
    value: 64
learning_rate:
    value: 0.001
model_type:
    value: multimodal
patience:
    value: 20
seed:
    value: 42
subset:
    value: 0
vf_width:
    value: 128
warmup_epochs:
    value: 5
weight_decay:
    value: 0.0001
